/**
 * packages/seed/src/tools.ts
 *
 * 도구 카탈로그 — `docs/TOOLS.md` §A를 그대로 옮긴 것.
 *
 * ★ 문서는 "48종"이라고 적었지만 표의 실제 행 수는 78이다. 한 행이 여러 도구를
 *   묶은 경우("아사나 / 트렐로 / 먼데이")를 1종으로 세도 78이다. 여기서는
 *   **표의 행을 하나도 버리지 않는 쪽**을 택했다. 카탈로그에서 빠진 도구는
 *   본문 추출에서 자유 텍스트로 떨어지고, 그러면 정규화 사전이 그만큼 얇아진다.
 *
 * `aliases`는 정규화 사전이다. **두 도구가 같은 동의어를 가지면 사전이 모호해진다** —
 * `test/seed.test.ts`가 그 충돌을 막는다.
 */

import type { ToolEntry } from './types.ts';

const node = (nodeType: string) => ({ kind: 'node' as const, nodeType });
const http = { kind: 'http' as const };
const none = { kind: 'none' as const };

export const TOOLS: readonly ToolEntry[] = [
  /* ── 커뮤니케이션 ──────────────────────────────────────────────────────── */
  {
    id: 'kakaotalk',
    name: '카카오톡',
    aliases: ['카톡', '단톡방', '카톡방', 'KakaoTalk'],
    connectivity: 'low',
    category: 'comm',
    n8n: none,
    rationale: '개인 대화 API 없음. 알림톡만 발신 가능, 수신·조회 불가',
    source: 'TOOLS.md',
  },
  {
    id: 'kakao-alimtalk',
    name: '카카오 알림톡',
    aliases: ['알림톡', '비즈메시지', '친구톡'],
    connectivity: 'high',
    category: 'comm',
    n8n: http,
    rationale: '발신 API 성숙(솔라피/NHN). 고객 통지 자동화의 국내 표준',
    source: 'TOOLS.md',
  },
  {
    id: 'slack',
    name: '슬랙',
    aliases: ['Slack', '슬렉', 'DM'],
    connectivity: 'high',
    category: 'comm',
    n8n: node('slack'),
    rationale: 'Web API + Events + Webhook 완비',
    source: 'TOOLS.md',
  },
  {
    id: 'naver-works',
    name: '네이버웍스',
    aliases: ['웍스', '라인웍스'],
    connectivity: 'mid',
    category: 'comm',
    n8n: http,
    rationale: 'Developers API 존재, 기성 노드 없음',
    source: 'TOOLS.md',
  },
  {
    id: 'jandi',
    name: '잔디',
    aliases: ['JANDI', '잔디 토픽'],
    connectivity: 'mid',
    category: 'comm',
    n8n: http,
    rationale: 'Incoming Webhook, 수신 API 제한적',
    source: 'TOOLS.md',
  },
  {
    id: 'ms-teams',
    name: 'MS 팀즈',
    aliases: ['Teams', '팀즈'],
    connectivity: 'high',
    category: 'comm',
    n8n: node('microsoftTeams'),
    rationale: 'Graph API 전면 지원',
    source: 'TOOLS.md',
  },
  {
    id: 'phone',
    name: '전화',
    aliases: ['유선', '폰', '통화', '콜'],
    connectivity: 'low',
    category: 'comm',
    n8n: none,
    rationale:
      '기록 자체가 없음. 이 제품의 존재 이유 — 프로세스/태스크 마이닝 완전 사각지대',
    source: 'TOOLS.md',
  },
  {
    id: 'sms',
    name: '문자(SMS)',
    aliases: ['문자', 'SMS', 'LMS'],
    connectivity: 'high',
    category: 'comm',
    n8n: http,
    rationale: '발송 대행 API 보편(알리고·솔라피)',
    source: 'TOOLS.md',
  },

  /* ── 메일 ──────────────────────────────────────────────────────────────── */
  {
    id: 'outlook',
    name: '아웃룩',
    aliases: ['Outlook', 'MS 메일'],
    connectivity: 'high',
    category: 'mail',
    n8n: node('microsoftOutlook'),
    source: 'TOOLS.md',
  },
  {
    id: 'gmail',
    name: '지메일 / 구글 워크스페이스',
    aliases: ['Gmail', '구글 메일', 'G메일'],
    connectivity: 'high',
    category: 'mail',
    n8n: node('gmail'),
    source: 'TOOLS.md',
  },
  {
    id: 'imap-mail',
    name: '사내 메일(IMAP)',
    aliases: ['회사메일', '다음스마트워크', '메일플러그'],
    connectivity: 'mid',
    category: 'mail',
    n8n: node('emailReadImap'),
    source: 'TOOLS.md',
  },

  /* ── 문서 · 스프레드시트 ──────────────────────────────────────────────── */
  {
    id: 'excel',
    name: '엑셀',
    aliases: ['액셀', 'Excel', '스프레드시트', 'xlsx'],
    connectivity: 'mid',
    category: 'doc',
    n8n: node('microsoftExcel'),
    rationale:
      '로컬 파일은 API 없음. OneDrive/SharePoint 저장 시 상으로 승격. 조직 내 최다 사용 도구이자 최대 자동화 장벽',
    upgrade: { toolId: 'google-sheets', note: '엑셀→구글시트 이전만으로 연결성이 중→상으로 뛴다' },
    source: 'TOOLS.md',
  },
  {
    id: 'google-sheets',
    name: '구글시트',
    aliases: ['구글 스프레드시트', '지시트', '시트'],
    connectivity: 'high',
    category: 'doc',
    n8n: node('googleSheets'),
    rationale: 'Sheets API 완전 지원',
    source: 'TOOLS.md',
  },
  {
    id: 'hwp',
    name: '한글(HWP)',
    aliases: ['아래아한글', 'hwp', '한컴'],
    connectivity: 'low',
    category: 'doc',
    n8n: none,
    rationale:
      '표준 API 없음. 국내 공문·계약서·품의서의 기본 포맷 → 국내 자동화 최대 병목 중 하나',
    source: 'TOOLS.md',
  },
  {
    id: 'word',
    name: '워드',
    aliases: ['Word', 'docx'],
    connectivity: 'mid',
    category: 'doc',
    n8n: node('microsoftOneDrive'),
    rationale: 'Graph API 조작 가능',
    source: 'TOOLS.md',
  },
  {
    id: 'powerpoint',
    name: '파워포인트',
    aliases: ['PPT', '피피티', '장표'],
    connectivity: 'low',
    category: 'doc',
    n8n: none,
    rationale: '생성은 가능하나 실무는 수작업 편집',
    source: 'TOOLS.md',
  },
  {
    id: 'notion',
    name: '노션',
    aliases: ['Notion', '노션 DB'],
    connectivity: 'high',
    category: 'doc',
    n8n: node('notion'),
    rationale: 'API 성숙. 경쟁 도구이면서 연동 대상',
    source: 'TOOLS.md',
  },
  {
    id: 'google-drive',
    name: '구글 드라이브',
    aliases: ['드라이브', '지드라이브'],
    connectivity: 'high',
    category: 'doc',
    n8n: node('googleDrive'),
    rationale: '파일 트리거',
    source: 'TOOLS.md',
  },
  {
    id: 'dropbox-onedrive',
    name: '드롭박스 / 원드라이브',
    aliases: ['드박', 'OneDrive'],
    connectivity: 'high',
    category: 'doc',
    n8n: node('dropbox'),
    rationale: '표준 API',
    source: 'TOOLS.md',
  },
  {
    id: 'figma',
    name: '피그마',
    aliases: ['Figma'],
    connectivity: 'mid',
    category: 'doc',
    n8n: http,
    rationale: 'REST API 읽기 위주',
    source: 'TOOLS.md',
  },

  /* ── 그룹웨어 · 전자결재 ──────────────────────────────────────────────── */
  {
    id: 'groupware-approval',
    name: '그룹웨어 전자결재',
    aliases: ['결재', '전자결재', '상신', '품의', '결재올리기'],
    connectivity: 'mid',
    category: 'groupware',
    n8n: http,
    rationale: '제품별 편차 큼. 대부분 폐쇄',
    source: 'TOOLS.md',
  },
  {
    id: 'douzone-wehago',
    name: '더존 위하고',
    aliases: ['위하고', 'WEHAGO'],
    connectivity: 'mid',
    category: 'groupware',
    n8n: http,
    rationale: 'Open API(계약 필요)',
    source: 'TOOLS.md',
  },
  {
    id: 'daouoffice',
    name: '다우오피스',
    aliases: ['다우'],
    connectivity: 'mid',
    category: 'groupware',
    n8n: http,
    rationale: 'API(유료 옵션)',
    source: 'TOOLS.md',
  },
  {
    id: 'hiworks',
    name: '하이웍스',
    aliases: ['Hiworks'],
    connectivity: 'mid',
    category: 'groupware',
    n8n: http,
    rationale: '일부 API',
    source: 'TOOLS.md',
  },
  {
    id: 'flow',
    name: '플로우',
    aliases: ['flow'],
    connectivity: 'mid',
    category: 'groupware',
    n8n: http,
    rationale: 'API 제공',
    source: 'TOOLS.md',
  },

  /* ── ERP · 회계 ───────────────────────────────────────────────────────── */
  {
    id: 'douzone-erp',
    name: '더존 ERP',
    aliases: ['더존', 'iCUBE', '아이큐브', 'SmartA'],
    connectivity: 'mid',
    category: 'erp',
    n8n: http,
    rationale: 'DB 직접 접근 또는 파일 업/다운로드가 현실적. Open API 제한적',
    upgrade: { toolId: 'ecount', note: '이카운트로 옮기면 Open API가 열려 상이 된다' },
    source: 'TOOLS.md',
  },
  {
    id: 'younglimwon',
    name: '영림원 K-System',
    aliases: ['영림원', 'K시스템'],
    connectivity: 'mid',
    category: 'erp',
    n8n: http,
    rationale: '커스터마이징 전제',
    source: 'TOOLS.md',
  },
  {
    id: 'ecount',
    name: '이카운트 ERP',
    aliases: ['이카운트', 'ECOUNT'],
    connectivity: 'high',
    category: 'erp',
    n8n: http,
    rationale: 'Open API 공개·문서화 양호. 중소기업 자동화 최적 진입점',
    source: 'TOOLS.md',
  },
  {
    id: 'sap',
    name: 'SAP',
    aliases: ['SAP ERP', 'S/4'],
    connectivity: 'mid',
    category: 'erp',
    n8n: http,
    rationale: 'OData/BAPI 존재하나 내부 승인 장벽',
    source: 'TOOLS.md',
  },
  {
    id: 'gyeongrinara',
    name: '경리나라',
    aliases: ['웹케시 경리나라'],
    connectivity: 'mid',
    category: 'erp',
    n8n: http,
    rationale: '뱅킹 연동 특화',
    source: 'TOOLS.md',
  },

  /* ── 세무 · 4대보험 · 전자세금계산서 ─────────────────────────────────── */
  {
    id: 'hometax',
    name: '홈택스',
    aliases: ['국세청', '세금계산서 발행'],
    connectivity: 'mid',
    category: 'tax',
    n8n: none,
    rationale: '공식 API 없음. 공동인증서 스크래핑 또는 ASP 경유가 실무 표준',
    upgrade: { toolId: 'barobill', note: '전자세금계산서 ASP(바로빌) 전환 시 상. 월 3~5만 원' },
    source: 'TOOLS.md',
  },
  {
    id: 'barobill',
    name: '바로빌',
    aliases: ['바로빌 API'],
    connectivity: 'high',
    category: 'tax',
    n8n: http,
    rationale: '전자세금계산서 발행 API 공개. 홈택스 대체 경로',
    source: 'TOOLS.md',
  },
  {
    id: 'smartbill',
    name: '스마트빌',
    aliases: ['비즈니스온'],
    connectivity: 'high',
    category: 'tax',
    n8n: http,
    rationale: 'API 제공',
    source: 'TOOLS.md',
  },
  {
    id: 'insurance4',
    name: '4대보험 정보연계센터',
    aliases: ['4대보험', '사대보험', '취득신고'],
    connectivity: 'low',
    category: 'tax',
    n8n: none,
    rationale: '공동인증서 + 화면 입력. API 없음',
    source: 'TOOLS.md',
  },
  {
    id: 'wetax',
    name: '위택스 / 이택스',
    aliases: ['지방세'],
    connectivity: 'low',
    category: 'tax',
    n8n: none,
    rationale: 'API 없음',
    source: 'TOOLS.md',
  },

  /* ── 은행 · 카드 · 결제 ───────────────────────────────────────────────── */
  {
    id: 'corp-banking',
    name: '기업 인터넷뱅킹',
    aliases: ['뱅킹', '인뱅', '법인뱅킹'],
    connectivity: 'mid',
    category: 'bank',
    n8n: http,
    rationale: '펌뱅킹/오픈뱅킹 계약 시 상',
    source: 'TOOLS.md',
  },
  {
    id: 'card-web',
    name: '법인카드 웹명세',
    aliases: ['카드 명세', '신한/삼성/현대 카드', '법인카드'],
    connectivity: 'low',
    category: 'bank',
    n8n: none,
    rationale: '개별 카드사 로그인·엑셀 다운로드. 통합 API 부재',
    upgrade: { toolId: 'crefia', note: '여신금융협회 매입자료 일괄 조회로 대체하면 중' },
    source: 'TOOLS.md',
  },
  {
    id: 'crefia',
    name: '여신금융협회 카드매출',
    aliases: ['여신협회'],
    connectivity: 'mid',
    category: 'bank',
    n8n: http,
    rationale: '매입자료 일괄 조회',
    source: 'TOOLS.md',
  },
  {
    id: 'pg',
    name: 'PG (토스페이먼츠/이니시스/KCP)',
    aliases: ['PG', '결제대행'],
    connectivity: 'high',
    category: 'bank',
    n8n: http,
    rationale: '결제·취소·조회 API 완비',
    source: 'TOOLS.md',
  },

  /* ── 인사 · 근태 · 채용 ───────────────────────────────────────────────── */
  { id: 'flex', name: 'flex', aliases: ['플렉스'], connectivity: 'mid', category: 'hr', n8n: http, source: 'TOOLS.md' },
  { id: 'shiftee', name: '시프티', aliases: ['Shiftee'], connectivity: 'mid', category: 'hr', n8n: http, source: 'TOOLS.md' },
  { id: 'albam', name: '알밤', aliases: ['알밤 출퇴근'], connectivity: 'low', category: 'hr', n8n: none, source: 'TOOLS.md' },
  { id: 'newploy', name: '뉴플로이', aliases: ['급여 계산'], connectivity: 'mid', category: 'hr', n8n: http, source: 'TOOLS.md' },
  {
    id: 'saramin',
    name: '사람인',
    aliases: ['saramin'],
    connectivity: 'mid',
    category: 'hr',
    n8n: http,
    rationale: '검색 API만. 공고 등록·지원자 조회 폐쇄',
    source: 'TOOLS.md',
  },
  { id: 'jobkorea', name: '잡코리아', aliases: ['잡코'], connectivity: 'low', category: 'hr', n8n: none, source: 'TOOLS.md' },
  { id: 'wanted', name: '원티드', aliases: ['wanted'], connectivity: 'mid', category: 'hr', n8n: http, source: 'TOOLS.md' },
  { id: 'greeting', name: '그리팅', aliases: ['greeting ATS'], connectivity: 'mid', category: 'hr', n8n: http, source: 'TOOLS.md' },

  /* ── 영업 · CRM · CS ──────────────────────────────────────────────────── */
  {
    id: 'salesforce',
    name: '세일즈포스',
    aliases: ['Salesforce', 'SFDC'],
    connectivity: 'high',
    category: 'crm',
    n8n: node('salesforce'),
    rationale: '완전한 API',
    source: 'TOOLS.md',
  },
  {
    id: 'hubspot',
    name: '허브스팟',
    aliases: ['HubSpot'],
    connectivity: 'high',
    category: 'crm',
    n8n: node('hubspot'),
    rationale: '완전한 API',
    source: 'TOOLS.md',
  },
  {
    id: 'remember',
    name: '리멤버',
    aliases: ['명함앱'],
    connectivity: 'low',
    category: 'crm',
    n8n: none,
    rationale: '개인 데이터 폐쇄',
    source: 'TOOLS.md',
  },
  {
    id: 'sales-ledger',
    name: '영업관리 대장(엑셀)',
    aliases: ['영업대장', '파이프라인 시트', '견적대장'],
    connectivity: 'mid',
    category: 'crm',
    n8n: node('spreadsheetFile'),
    rationale: '실체는 엑셀. 국내 중소기업 CRM의 실제 1위',
    upgrade: { toolId: 'google-sheets', note: '구글시트로만 옮겨도 조회·집계가 API로 열린다' },
    source: 'TOOLS.md',
  },
  {
    id: 'channeltalk',
    name: '채널톡',
    aliases: ['channel.io'],
    connectivity: 'high',
    category: 'crm',
    n8n: http,
    rationale: 'Open API + 웹훅',
    source: 'TOOLS.md',
  },
  {
    id: 'zendesk',
    name: '젠데스크',
    aliases: ['Zendesk'],
    connectivity: 'high',
    category: 'crm',
    n8n: node('zendesk'),
    rationale: '성숙한 API',
    source: 'TOOLS.md',
  },
  {
    id: 'happytalk',
    name: '해피톡',
    aliases: ['happytalk'],
    connectivity: 'mid',
    category: 'crm',
    n8n: http,
    rationale: 'API 일부',
    source: 'TOOLS.md',
  },
  {
    id: 'callcenter',
    name: '콜센터/ARS',
    aliases: ['인바운드', '대표번호'],
    connectivity: 'low',
    category: 'crm',
    n8n: none,
    rationale: '통화 비구조화. 녹취 STT 시 중으로 승격',
    source: 'TOOLS.md',
  },

  /* ── 이커머스 · 물류 ──────────────────────────────────────────────────── */
  { id: 'smartstore', name: '스마트스토어', aliases: ['네이버 스토어', '스토어팜'], connectivity: 'high', category: 'commerce', n8n: http, source: 'TOOLS.md' },
  { id: 'coupang-wing', name: '쿠팡 윙', aliases: ['쿠팡', 'WING'], connectivity: 'high', category: 'commerce', n8n: http, source: 'TOOLS.md' },
  { id: 'cafe24', name: '카페24', aliases: ['cafe24', '자사몰'], connectivity: 'high', category: 'commerce', n8n: http, source: 'TOOLS.md' },
  {
    id: 'ezadmin',
    name: '이지어드민',
    aliases: ['ezadmin'],
    connectivity: 'mid',
    category: 'commerce',
    n8n: http,
    rationale: '국내 3PL·셀러 표준',
    source: 'TOOLS.md',
  },
  { id: 'sabangnet', name: '사방넷 / 플레이오토', aliases: ['사방넷', '플오'], connectivity: 'mid', category: 'commerce', n8n: http, source: 'TOOLS.md' },
  {
    id: 'courier',
    name: '택배사 시스템',
    aliases: ['CJ대한통운', '롯데택배', '한진', '우체국', '송장'],
    connectivity: 'mid',
    category: 'commerce',
    n8n: http,
    source: 'TOOLS.md',
  },

  /* ── 마케팅 ───────────────────────────────────────────────────────────── */
  { id: 'meta-business', name: '메타 비즈니스', aliases: ['페이스북 광고', '인스타 광고'], connectivity: 'high', category: 'marketing', n8n: node('facebookGraphApi'), source: 'TOOLS.md' },
  { id: 'naver-ads', name: '네이버 검색광고', aliases: ['네이버 광고', '파워링크'], connectivity: 'high', category: 'marketing', n8n: http, source: 'TOOLS.md' },
  { id: 'google-ads', name: '구글애즈', aliases: ['Google Ads'], connectivity: 'high', category: 'marketing', n8n: node('googleAds'), source: 'TOOLS.md' },
  { id: 'ga4', name: 'GA4', aliases: ['구글 애널리틱스'], connectivity: 'high', category: 'marketing', n8n: node('googleAnalytics'), source: 'TOOLS.md' },
  { id: 'stibee', name: '스티비', aliases: ['stibee'], connectivity: 'high', category: 'marketing', n8n: http, source: 'TOOLS.md' },
  {
    id: 'instagram-youtube',
    name: '인스타그램 / 유튜브',
    aliases: ['인스타', 'IG'],
    connectivity: 'mid',
    category: 'marketing',
    n8n: node('youTube'),
    rationale: '게시 API 제한',
    source: 'TOOLS.md',
  },
  {
    id: 'wordpress-naverblog',
    name: '워드프레스 / 네이버 블로그',
    aliases: ['워프', '블로그'],
    connectivity: 'mid',
    category: 'marketing',
    n8n: node('wordpress'),
    rationale: '워드프레스는 상, 네이버 블로그는 하(API 종료). 한 행에 두 실체가 섞여 있다',
    source: 'TOOLS.md',
  },

  /* ── 프로젝트 · 전자계약 ──────────────────────────────────────────────── */
  { id: 'jira', name: '지라', aliases: ['Jira', '티켓', '이슈'], connectivity: 'high', category: 'project', n8n: node('jira'), source: 'TOOLS.md' },
  {
    id: 'asana-trello-monday',
    name: '아사나 / 트렐로 / 먼데이',
    aliases: ['Asana', 'Trello', 'monday'],
    connectivity: 'high',
    category: 'project',
    n8n: node('asana'),
    rationale: '세 도구가 한 행. n8n 노드는 각각 asana / trello / mondayCom',
    source: 'TOOLS.md',
  },
  { id: 'modusign', name: '모두싸인', aliases: ['modusign'], connectivity: 'high', category: 'project', n8n: http, rationale: '서명 완료 웹훅', source: 'TOOLS.md' },
  { id: 'eformsign', name: '이폼사인', aliases: ['eformsign'], connectivity: 'high', category: 'project', n8n: http, source: 'TOOLS.md' },
  {
    id: 'cert',
    name: '공동인증서',
    aliases: ['공인인증서', '인증서', '금융인증서'],
    connectivity: 'low',
    category: 'project',
    n8n: none,
    rationale: '자동화 최대 장벽. 무인 실행이 사실상 불가',
    feasibilityCap: 0.5,
    source: 'TOOLS.md',
  },

  /* ── 오프라인 · 물리 ──────────────────────────────────────────────────── */
  {
    id: 'paper',
    name: '종이 서류',
    aliases: ['서류', '출력물', '프린트', '결재판', '스캔'],
    connectivity: 'low',
    category: 'offline',
    n8n: none,
    rationale: '스캔+OCR 시 중으로 승격',
    source: 'TOOLS.md',
  },
  {
    id: 'seal',
    name: '법인인감 / 사용인감',
    aliases: ['인감', '도장', '날인', '직인'],
    connectivity: 'low',
    category: 'offline',
    n8n: none,
    rationale: '전자계약 전환 시 상',
    upgrade: { toolId: 'modusign', note: '모두싸인 전자계약으로 전환하면 상' },
    source: 'TOOLS.md',
  },
  {
    id: 'oral-request',
    name: '구두 요청',
    aliases: ['말로', '옆자리에서', '지나가면서', '회의 때'],
    connectivity: 'low',
    category: 'offline',
    n8n: none,
    rationale:
      '기록 자체가 존재하지 않음. 이 도구가 붙은 단계는 "문서화 가치 최상"으로 표시',
    source: 'TOOLS.md',
  },
  {
    id: 'barcode',
    name: '바코드 스캐너',
    aliases: ['스캐너', '리더기'],
    connectivity: 'mid',
    category: 'offline',
    n8n: http,
    rationale: '창고 시스템 경유',
    source: 'TOOLS.md',
  },
  { id: 'whiteboard', name: '화이트보드 / 포스트잇', aliases: ['보드', '칠판'], connectivity: 'low', category: 'offline', n8n: none, source: 'TOOLS.md' },

  /* ── 시드를 쓰다가 필요해진 행 ────────────────────────────────────────
   * TOOLS.md 운영 규칙 2가 말하는 "미매칭 상위 N건 → 카탈로그 확장 큐"의
   * 첫 입주자들. 여기 있다는 것 자체가 문서에 구멍이 있었다는 기록이다. */
  {
    id: 'label-printer',
    name: '라벨프린터',
    aliases: ['라벨기', '자산라벨'],
    connectivity: 'low',
    category: 'offline',
    n8n: none,
    rationale: 'GA-01 11번 자산 등록에 실제로 등장하는데 TOOLS.md 표에는 없다',
    source: 'seed-extension',
  },
  {
    id: 'wms',
    name: '창고 재고 시스템(WMS)',
    aliases: ['WMS', '재고시스템', '피킹리스트'],
    connectivity: 'mid',
    category: 'commerce',
    n8n: http,
    rationale: 'OPS-01 피킹·재고 차감이 이지어드민만으로 설명되지 않는다',
    source: 'seed-extension',
  },
];

export const TOOL_BY_ID: ReadonlyMap<string, ToolEntry> = new Map(TOOLS.map((t) => [t.id, t]));

/**
 * 정규화 사전. 동의어 → 도구 ID.
 * 충돌이 있으면 사전이 모호해지므로 테스트가 먼저 막는다.
 */
export const TOOL_ALIAS_INDEX: ReadonlyMap<string, string> = new Map(
  TOOLS.flatMap((t) => [
    [t.name.toLowerCase(), t.id] as const,
    ...t.aliases.map((a) => [a.toLowerCase(), t.id] as const),
  ]),
);

/** 연결성 '하' 도구. 배제 대상이 아니라 **선행 개선 제안 대상**이다 */
export const LOW_CONNECTIVITY_TOOL_IDS: readonly string[] = TOOLS.filter(
  (t) => t.connectivity === 'low',
).map((t) => t.id);

/** Feasibility 상한을 거는 도구 (지금은 공동인증서 하나) */
export const FEASIBILITY_CAPPING_TOOL_IDS: readonly string[] = TOOLS.filter(
  (t) => typeof t.feasibilityCap === 'number',
).map((t) => t.id);
